java_library(
    name = "dropwizard-jersey",
    srcs = glob(["dropwizard-jersey/src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@com_codahale_metrics_metrics_annotation//jar",
        "@com_codahale_metrics_metrics_core//jar",
        "@com_codahale_metrics_metrics_jersey//jar",
        "@com_fasterxml_jackson_core_jackson_annotations//jar",
        "@com_fasterxml_jackson_core_jackson_core//jar",
        "@com_fasterxml_jackson_core_jackson_databind//jar",
        "@com_fasterxml_jackson_jaxrs_jackson_jaxrs_base//jar",
        "@com_fasterxml_jackson_jaxrs_jackson_jaxrs_json_provider//jar",
        "@com_fasterxml_jackson_module_jackson_module_jaxb_annotations//jar",
        "@com_google_code_findbugs_jsr305//jar",
        "@com_google_guava_guava//jar",
        "@com_sun_jersey_jersey_core//jar",
        "@com_sun_jersey_jersey_server//jar",
        "@com_sun_jersey_jersey_servlet//jar",
        "@io_dropwizard_dropwizard_jackson//jar",
        "@io_dropwizard_dropwizard_logging//jar",
        "@io_dropwizard_dropwizard_validation//jar",
        "@javax_validation_validation_api//jar",
        "@joda_time_joda_time//jar",
        "@org_eclipse_jetty_orbit_javax_servlet//jar",
        "@org_slf4j_slf4j_api//jar",
    ],
)
